# Decission Tree

In [1]:
# from google.colab import files
# uploaded = files.upload()

In [2]:
import pandas as pd

In [3]:
from sklearn.preprocessing import StandardScaler # data preprocessing -> normalisasi data (pakai transformasi Z-Score)
from sklearn.model_selection import train_test_split # memecah data training dan data testing
from sklearn.metrics import mean_squared_error # ukuran akurasi
from sklearn.metrics import accuracy_score # ukuran akurasi
from sklearn.metrics import confusion_matrix # ukuran akurasi
from sklearn.metrics import classification_report # ukuran akurasi
from sklearn.model_selection import StratifiedKFold, cross_val_score,GridSearchCV # ukuran akurasi
from sklearn.preprocessing import LabelEncoder # data preprocessing -> discreatisasi
from datetime import datetime, timedelta, date # jika butuh data tanggal/waktu
import numpy as np # 
import matplotlib.pyplot as plt # visualisasi data
from sklearn.tree import DecisionTreeClassifier # import algoritma
from sklearn import tree
from sklearn.metrics import plot_confusion_matrix

In [5]:
df = pd.read_csv('D:\kuliah\smt 7\kecerdasan bisnis\praktisi\Data Impor\diabetes.csv')

In [6]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
# mengecek jumlah data kosong
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
# memisahkan variabel X dan y
# X = gejala/tanda - tanda diabetes
feature_cols = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']
X = df[feature_cols]
y = df.Outcome

In [11]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [12]:
# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# test_size = 0.30 artinya proporsi data testing adalah 30% dari total data

In [13]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
334,1,95,60,18,58,23.9,0.260,22
139,5,105,72,29,325,36.9,0.159,28
485,0,135,68,42,250,42.3,0.365,24
547,4,131,68,21,166,33.1,0.160,28
18,1,103,30,38,83,43.3,0.183,33
...,...,...,...,...,...,...,...,...
71,5,139,64,35,140,28.6,0.411,26
106,1,96,122,0,0,22.4,0.207,27
270,10,101,86,37,0,45.6,1.136,38
435,0,141,0,0,0,42.4,0.205,29
102,0,125,96,0,0,22.5,0.262,21

In [14]:
# modeling
# modeling menggunakan DEcisionTree
fit = DecisionTreeClassifier().fit(X_train, y_train.values.ravel())
y_pred = fit.predict(X_test) # prediction

In [15]:
X_test['y_pred'] = y_pred
X_test['y_asli'] = y_test
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,y_pred,y_asli
668,6,98,58,33,190,34.0,0.430,43,0,0
324,2,112,75,32,0,35.7,0.148,21,1,0
624,2,108,64,0,0,30.8,0.158,21,0,0
690,8,107,80,0,0,24.6,0.856,34,0,0
473,7,136,90,0,0,29.9,0.210,50,0,0
...,...,...,...,...,...,...,...,...,...,...
619,0,119,0,0,0,32.4,0.141,24,0,1
198,4,109,64,44,99,34.8,0.905,26,0,1
538,0,127,80,37,210,36.3,0.804,23,0,0
329,6,105,70,32,68,30.8,0.122,37,0,0
302,5,77,82,41,42,35.8,0.156,35,0,0

In [16]:
confusion_matriks = confusion_matrix(y_test, y_pred)
classification_reports = classification_report(y_test, y_pred)

In [17]:
print(confusion_matriks)

[[109  42]
 [ 26  54]]

In [18]:
print(classification_reports)

              precision    recall  f1-score   support

           0       0.81      0.72      0.76       151
           1       0.56      0.68      0.61        80

    accuracy                           0.71       231
   macro avg       0.68      0.70      0.69       231
weighted avg       0.72      0.71      0.71       231

In [19]:
# variable importance
"""
Variabel mana yang paling penting dapat dilihat di bagian ini
"""
df_importance = pd.DataFrame(fit.feature_importances_).T
df_importance.columns = feature_cols
df_importance2 = df_importance.T.reset_index()
df_importance2.columns = ['variabel','relatif_importance']
df_importance2 = df_importance2.sort_values('relatif_importance',ascending=False)
df_importance2

                   variabel  relatif_importance
1                   Glucose            0.348412
5                       BMI            0.204047
7                       Age            0.115865
2             BloodPressure            0.102479
6  DiabetesPedigreeFunction            0.096871
3             SkinThickness            0.059654
4                   Insulin            0.047054
0               Pregnancies            0.025618

In [20]:
fit.feature_importances_

array([0.02561804, 0.34841166, 0.10247943, 0.05965444, 0.04705396,
       0.20404671, 0.09687065, 0.11586512])